version: '3'

services:
  proxy:
    image: ghcr.io/bedroom-developers/sentry-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      CERTBOT_EMAIL: admin@ispark.kz
      CERTBOT_AUTHENTICATOR: dns-cloudflare
      STAGING: "0"
      USE_ECDSA: "1"
      RENEWAL_INTERVAL: 8d
    volumes:
      - ./nginx/cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
      - ./nginx/nginx.conf.d:/etc/nginx/user_conf.d:ro
      - letsencrypt:/etc/letsencrypt

volumes:
  letsencrypt:
