upstream relay {
    server relay:3000;
    keepalive 2;
}

upstream sentry {
    server web:9000;
    keepalive 2;
}

server {
    listen 443 ssl default_server reuseport;
    listen [::]:443 ssl default_server reuseport;
    server_name debug.ispark.kz;

    ssl_certificate         /etc/letsencrypt/live/debug.ispark.kz/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/debug.ispark.kz/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/debug.ispark.kz/chain.pem;

    ssl_dhparam /etc/letsencrypt/dhparams/dhparam.pem;

    location /api/store/ {
        proxy_pass http://relay;
    }

    location ~ ^/api/[1-9]\d*/ {
        proxy_pass http://relay;
    }

    location ^~ /api/0/relays/ {
        proxy_pass http://relay;
    }

    location ^~ /js-sdk/ {
        root /var/www/;
        add_header Access-Control-Allow-Origin *;
    }

    location / {
        proxy_pass http://sentry;
        proxy_set_header Connection "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Request-Id $request_id;
        proxy_read_timeout 30s;
        proxy_send_timeout 5s;

	proxy_hide_header X-Frame-Options;
	add_header Content-Security-Policy "frame-ancestors 'self' https://yekinsgns-macbook-pro-1.mulley-typhon.ts.net https://dev.ispark.kz http://localhost:3000;" always;
    }

    location /_assets/ {
        proxy_pass http://sentry/_static/dist/sentry/;
        proxy_hide_header Content-Disposition;
    }

    location /_static/ {
        proxy_pass http://sentry;
        proxy_hide_header Content-Disposition;
    }
}